### ISSUE TITLE
Cannot find module './rateLimiter.mjs'

### ISSUE THREAD

**Issue by apski** [dutu/rate-limiter#2]
Hey I tried to use this together with your throttled-queue but got this error: 

```
 Cannot find module './rateLimiter.mjs' from 'node_modules/@dutu/rate-limiter/dist/index.js'

    Require stack:
      node_modules/@dutu/rate-limiter/dist/index.js
```

Do you know what it could be?

Thanks

**Comment by dutu** [comment]
It looks that there was an error when using the module with `require` (rather than `import`).
Please try the newly released version [v1.1.6](https://github.com/dutu/rate-limiter/releases/tag/v1.1.6).

**Comment by apski** [comment]
Thanks - that solves that. 

I'm now having a problem with throttled-queue: 

```
 Cannot find module '@dutu/throttled-queue' or its corresponding type declarations.

    import ThrottledQueue from "@dutu/throttled-queue"
```

Would it be something similar?

**Comment by dutu** [comment]
have done an update and included a note if you are using the package as CommonJS module (`require`)
https://github.com/dutu/throttled-queue/blob/master/README.md#installation
